import React, { createContext, useContext, useState, useCallback } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    // Nav
    navNews: 'News',
    navArena: 'Agent Arena',
    navHistory: 'History',
    navStocks: 'Stocks',
    navLeaderboard: 'Leaderboard',
    navPortfolio: 'Portfolio',
    navLogout: 'Logout',
    // Arena
    arenaTitle: 'Vantage AI Agent Arena',
    arenaSubtitle: 'Multi-agent adversarial debate engine for Kuwait & GCC markets',
    launchAnalysis: 'Launch Analysis',
    sectorFocus: 'Sector Focus',
    timeHorizon: 'Time Horizon',
    marketBias: 'Market Bias',
    bullish: 'Bullish',
    bearish: 'Bearish',
    neutral: 'Neutral',
    shortTerm: 'Short',
    mediumTerm: 'Medium',
    longTerm: 'Long',
    agentWeights: 'Agent Weights',
    followUp: 'Ask a Follow-Up Question',
    followUpPlaceholder: 'Ask any agent a follow-up question...',
    scenarioTitle: 'What-If Scenario Mode',
    scenarioDesc: 'Inject a counterfactual event to see how the debate changes',
    scenarioPlaceholder: 'e.g. Oil prices drop to $50 unexpectedly',
    runScenario: 'Run Scenario',
    challengePlaceholder: "Challenge this agent's logic...",
    challenge: 'Challenge',
    createAgent: 'Create Custom Agent',
    agentName: 'Agent Name',
    agentRole: 'Agent Role',
    agentBrief: 'System Prompt / Brief',
    saveAgent: 'Save Agent',
    cancel: 'Cancel',
    custom: 'Custom',
    // Verdict
    consensusReport: 'Consensus Report',
    marketOutlook: 'Market Outlook',
    riskWarnings: 'Risk Warnings',
    topPicks: 'Top Stock Picks',
    disclaimer: 'Multi-agent AI analysis. Not financial advice. Generated by Vantage AI Terminal.',
    // General
    language: 'Language',
  },
  ar: {
    // Nav
    navNews: 'الأخبار',
    navArena: 'ساحة الوكلاء',
    navHistory: 'السجل',
    navStocks: 'الأسهم',
    navLeaderboard: 'لوحة الترتيب',
    navPortfolio: 'المحفظة',
    navLogout: 'تسجيل الخروج',
    // Arena
    arenaTitle: 'ساحة وكلاء الذكاء الاصطناعي - Vantage',
    arenaSubtitle: 'محرك مناظرة متعدد الوكلاء لأسواق الكويت والخليج',
    launchAnalysis: 'بدء التحليل',
    sectorFocus: 'تركيز القطاع',
    timeHorizon: 'الأفق الزمني',
    marketBias: 'توجه السوق',
    bullish: 'صعودي',
    bearish: 'هبوطي',
    neutral: 'محايد',
    shortTerm: 'قصير',
    mediumTerm: 'متوسط',
    longTerm: 'طويل',
    agentWeights: 'أوزان الوكلاء',
    followUp: 'اطرح سؤال متابعة',
    followUpPlaceholder: 'اسأل أي وكيل سؤال متابعة...',
    scenarioTitle: 'وضع السيناريو الافتراضي',
    scenarioDesc: 'أدخل حدثًا افتراضيًا لترى كيف يتغير النقاش',
    scenarioPlaceholder: 'مثال: أسعار النفط تنخفض إلى 50 دولار بشكل مفاجئ',
    runScenario: 'تشغيل السيناريو',
    challengePlaceholder: 'تحدَّ منطق هذا الوكيل...',
    challenge: 'تحدّي',
    createAgent: 'إنشاء وكيل مخصص',
    agentName: 'اسم الوكيل',
    agentRole: 'دور الوكيل',
    agentBrief: 'التعليمات / الوصف',
    saveAgent: 'حفظ الوكيل',
    cancel: 'إلغاء',
    custom: 'مخصص',
    // Verdict
    consensusReport: 'تقرير الإجماع',
    marketOutlook: 'توقعات السوق',
    riskWarnings: 'تحذيرات المخاطر',
    topPicks: 'أفضل الأسهم المختارة',
    disclaimer: 'تحليل ذكاء اصطناعي متعدد الوكلاء. ليس نصيحة مالية. تم إنشاؤه بواسطة Vantage AI Terminal.',
    // General
    language: 'اللغة',
  }
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en');

  const t = useCallback((key) => {
    return translations[lang]?.[key] || translations.en[key] || key;
  }, [lang]);

  const toggleLanguage = useCallback(() => {
    setLang(prev => prev === 'en' ? 'ar' : 'en');
  }, []);

  const isRTL = lang === 'ar';

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, toggleLanguage, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
